# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/QApp.h \
    ./src/source2.h \
    ./src/QAppWidget.h
SOURCES += ./src/main.cpp \
    ./src/QApp.cpp
